import java.awt.List;
import java.io.File;
import java.util.ArrayList;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.ibm.watson.developer_cloud.http.HttpMediaType;
import com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText;
import com.ibm.watson.developer_cloud.speech_to_text.v1.model.SpeechResults;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public static String lib(){
	  SpeechToText service = new SpeechToText();
	  service.setUsernameAndPassword("5964e6c0-17fe-4a26-93d8-165bc295fe8c", "OHwit101z21y");

	  File audio = new File("C:\\Users\\nimish.b.gupta\\Desktop\\final.wav");

	  SpeechResults transcript = service.recognize(audio).execute();
	  String s = transcript.toString();
	  s=jsonToString(s);
	  return s;
	  //System.out.println(transcript);
	  
    }
  
  public static String jsonToString(String s){
	  JsonParser parser = new JsonParser(); 
	  JsonObject json = (JsonObject) parser.parse(s);
	  System.out.println(json.get("results"));
	  JsonArray jsonArray = new JsonArray();
	  jsonArray = (JsonArray) json.get("results");
	  StringBuilder stringBuilder = new StringBuilder();
	  for (int i=0; i < jsonArray.size(); i++) {
		  JsonElement jsonElement = jsonArray.get(i);
		  json = jsonElement.getAsJsonObject();
		  for(int j=0; j<json.get("alternatives").getAsJsonArray().size(); j++){
			  JsonElement jsonElement2 = json.get("alternatives").getAsJsonArray().get(j);
			  stringBuilder.append(jsonElement2.getAsJsonObject().get("transcript").toString().substring(1,jsonElement2.getAsJsonObject().get("transcript").toString().length()-1));
		  }
		}
	  System.out.println("Final String is-->\n"+stringBuilder.toString());
	  return stringBuilder.toString();
  }
}
